"""empty message

Revision ID: 139b854ed80b
Revises: None
Create Date: 2014-11-25 23:59:20.884372

"""

# revision identifiers, used by Alembic.
revision = '139b854ed80b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
